name: Run from Jira

on:
  workflow_dispatch:
  repository_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Print full event
        run: |
          echo "Event name: ${{ github.event_name }}"
          echo "Action: ${{ github.event.action }}"
          echo '${{ toJson(github.event) }}'