name: Run from Jira
on:
  repository_dispatch:
    types:
      - jira_ticket_in_progress
  workflow_dispatch:
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Print jira payload
        run: |
          echo "Ticket: ${{ issue.key }}"
          echo "Summary: ${{ issue.summary.jsonEncode }}"
          echo "Status: ${{ issue.status.name }}"
          echo "url: ${{ issue.url }}"
          echo "Type: ${{ issue.issueType.name }}"
          echo "Priority: {{ issue.priority.name }}"
          echo "Assignee: {{ issue.assignee.dispayName }}"
          echo "Reporter: {{ issue.reporter.displayName }}"
          echo "Project: {{ issue.project.key }}"